# -*- coding: utf-8 -*-
"""V1_web_aplicaciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DP3pHTRunWNzCbTcAbOuXWL-jA7WtNjq
"""

import os
import json
import pandas as pd
import numpy as np
from dash import Dash, dcc, html, dash_table
import plotly.express as px
import unidecode

# ============================================================
# INICIALIZAR APP DASH
# ============================================================
from dash import Dash
import os

app = Dash(__name__)

app = Dash(__name__)
server = app.server

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8050))
    app.run(host="0.0.0.0", port=port, debug=False)
# ============================================================
# RUTAS DE ARCHIVOS
# ============================================================

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

archivo_mortalidad = os.path.join(BASE_DIR, "data", "NoFetal2019.xlsx")
archivo_codigos = os.path.join(BASE_DIR, "data", "CodigosDeMuerte.xlsx")
archivo_divipola = os.path.join(BASE_DIR, "data", "Divipola.xlsx")
archivo_geojson = os.path.join(BASE_DIR, "data", "depto.json")

import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

archivo_mortalidad = os.path.join(BASE_DIR, "data", "NoFetal2019.xlsx")

df = pd.read_excel(archivo_mortalidad)

# ============================================================
# CARGAR ARCHIVOS
# ============================================================

df = pd.read_excel(archivo_mortalidad)

# Cargar códigos de muerte
temp_codigos = pd.read_excel(archivo_codigos, header=None)

new_header = temp_codigos.iloc[8]

codigos = temp_codigos[9:].copy()

codigos.columns = new_header

codigos = codigos.reset_index(drop=True)

# Cargar divipola
divipola = pd.read_excel(archivo_divipola)

# Cargar geojson
with open(archivo_geojson, "r", encoding="utf-8") as f:
    geojson_colombia = json.load(f)

# ============================================================
# LIMPIAR NOMBRES DE COLUMNAS
# ============================================================

df.columns = df.columns.str.strip().str.upper()

codigos.columns = codigos.columns.str.strip().str.upper()

divipola.columns = divipola.columns.str.strip().str.upper()

# ============================================================
# RENOMBRAR COLUMNAS
# ============================================================

df = df.rename(columns={
    "COD_DEPARTAMENTO": "COD_DPTO",
    "COD_MUNICIPIO": "COD_MUNIC",
})

divipola = divipola.rename(columns={
    "COD_DEPARTAMENTO": "COD_DPTO",
    "COD_MUNICIPIO": "COD_MUNIC",
    "DEPARTAMENTO": "DPTO",
    "NOM_DPTO": "DPTO",
    "NOMBRE_DPTO": "DPTO",
    "NOM_MUNIC": "MUNICIPIO",
    "NOMBRE_MUNIC": "MUNICIPIO",
})

codigos = codigos.rename(columns={
    "CÓDIGO DE LA CIE-10 TRES CARACTERES": "CODIGO",
    "DESCRIPCIÓN  DE CÓDIGOS MORTALIDAD A TRES CARACTERES": "NOMBRE",
})

# ============================================================
# TIPOS DE DATOS
# ============================================================

df["COD_DPTO"] = df["COD_DPTO"].astype(str).str.zfill(2)

df["COD_MUNIC"] = df["COD_MUNIC"].astype(str).str.zfill(5)

df["MES"] = pd.to_numeric(df["MES"], errors="coerce")

df["SEXO"] = df["SEXO"].astype(str)

df["GRUPO_EDAD1"] = pd.to_numeric(df["GRUPO_EDAD1"], errors="coerce")

df["COD_MUERTE"] = df["COD_MUERTE"].astype(str).str.strip().str.upper()

divipola["COD_DPTO"] = divipola["COD_DPTO"].astype(str).str.zfill(2)

divipola["COD_MUNIC"] = divipola["COD_MUNIC"].astype(str).str.zfill(5)

codigos["CODIGO"] = codigos["CODIGO"].astype(str).str.strip().str.upper()

# ============================================================
# MERGE DE INFORMACIÓN
# ============================================================

divipola_dpto = divipola[["COD_DPTO", "DPTO"]].drop_duplicates()

divipola_munic = divipola[["COD_MUNIC", "MUNICIPIO"]].drop_duplicates()

df = df.merge(divipola_dpto, on="COD_DPTO", how="left")

df = df.merge(divipola_munic, on="COD_MUNIC", how="left")

df = df.merge(
    codigos.rename(columns={
        "CODIGO": "COD_MUERTE",
        "NOMBRE": "CAUSA_NOMBRE"
    }),
    on="COD_MUERTE",
    how="left"
)

# ============================================================
# NORMALIZAR DEPARTAMENTOS
# ============================================================

df["DPTO_NORMALIZADO"] = (
    df["DPTO"]
    .astype(str)
    .str.upper()
    .apply(unidecode.unidecode)
    .str.strip()
)

# ============================================================
# CORRECCIONES ESPECÍFICAS
# ============================================================

correcciones = {
    "BOGOTA, D.C.": "SANTAFE DE BOGOTA D.C",
    "ARCHIPIELAGO DE SAN ANDRES, PROVIDENCIA Y SANTA CATALINA":
        "ARCHIPIELAGO DE SAN ANDRES PROVIDENCIA Y SANTA CATALINA",
    "NARINO": "NARIÑO"
}

df["DPTO_NORMALIZADO"] = (
    df["DPTO_NORMALIZADO"]
    .replace(correcciones)
)

# ============================================================
# MAPA — MUERTES POR DEPARTAMENTO
# ============================================================

muertes_dpto = (
    df.groupby(["COD_DPTO", "DPTO", "DPTO_NORMALIZADO"])
    .size()
    .reset_index(name="TOTAL")
)

fig_mapa = px.choropleth(
    muertes_dpto,
    geojson=geojson_colombia,
    locations="DPTO_NORMALIZADO",
    featureidkey="properties.NOMBRE_DPT",
    color="TOTAL",
    hover_name="DPTO",
    color_continuous_scale="Reds",
    title="Distribución total de muertes por departamento — Colombia 2019"
)

fig_mapa.update_geos(
    fitbounds="locations",
    visible=False
)

fig_mapa.update_layout(
    margin={"r": 0, "t": 50, "l": 0, "b": 0}
)

# ============================================================
# GRÁFICO DE LÍNEAS — MUERTES POR MES
# ============================================================

meses_nombres = {
    1: "Ene",
    2: "Feb",
    3: "Mar",
    4: "Abr",
    5: "May",
    6: "Jun",
    7: "Jul",
    8: "Ago",
    9: "Sep",
    10: "Oct",
    11: "Nov",
    12: "Dic"
}

muertes_mes = (
    df.groupby("MES")
    .size()
    .reset_index(name="TOTAL")
)

muertes_mes = muertes_mes[muertes_mes["MES"].between(1, 12)]

muertes_mes["MES_NOMBRE"] = (
    muertes_mes["MES"]
    .map(meses_nombres)
)

fig_lineas = px.line(
    muertes_mes,
    x="MES_NOMBRE",
    y="TOTAL",
    markers=True,
    title="Total de muertes por mes — Colombia 2019"
)

# ============================================================
# GRÁFICO DE BARRAS — HOMICIDIOS X95
# ============================================================

homicidios = df[
    df["COD_MUERTE"]
    .str.match(r"^X95", na=False)
]

ciudades_violentas = (
    homicidios.groupby("MUNICIPIO")
    .size()
    .reset_index(name="HOMICIDIOS")
    .sort_values("HOMICIDIOS", ascending=False)
    .head(5)
)

fig_barras = px.bar(
    ciudades_violentas,
    x="MUNICIPIO",
    y="HOMICIDIOS",
    color="HOMICIDIOS",
    text="HOMICIDIOS",
    title="5 ciudades más violentas — Colombia 2019"
)

fig_barras.update_traces(textposition="outside")

# ============================================================
# GRÁFICO CIRCULAR — 10 CIUDADES MENOR MORTALIDAD
# ============================================================

ciudades_menor = (
    df.groupby("MUNICIPIO")
    .size()
    .reset_index(name="TOTAL")
    .sort_values("TOTAL", ascending=True)
    .head(10)
)

fig_pie = px.pie(
    ciudades_menor,
    names="MUNICIPIO",
    values="TOTAL",
    title="10 ciudades con menor índice de mortalidad"
)

# ============================================================
# TABLA — PRINCIPALES CAUSAS DE MUERTE
# ============================================================

top_causas = (
    df.groupby(["COD_MUERTE", "CAUSA_NOMBRE"])
    .size()
    .reset_index(name="TOTAL")
    .sort_values("TOTAL", ascending=False)
    .head(10)
)

# ============================================================
# BARRAS APILADAS — SEXO POR DEPARTAMENTO
# ============================================================

sexo_map = {
    "1": "Hombre",
    "2": "Mujer",
    "3": "Indeterminado"
}

df["SEXO_NOMBRE"] = (
    df["SEXO"]
    .map(sexo_map)
    .fillna("Otro")
)

muertes_sexo_dpto = (
    df.groupby(["DPTO", "SEXO_NOMBRE"])
    .size()
    .reset_index(name="TOTAL")
)

fig_apiladas = px.bar(
    muertes_sexo_dpto,
    x="DPTO",
    y="TOTAL",
    color="SEXO_NOMBRE",
    barmode="stack",
    title="Muertes por sexo en cada departamento"
)

fig_apiladas.update_layout(
    xaxis_tickangle=-45
)

# ============================================================
# HISTOGRAMA — GRUPOS DE EDAD
# ============================================================

fig_histograma = px.histogram(
    df,
    x="GRUPO_EDAD1",
    nbins=20,
    title="Distribución de muertes por grupo de edad"
)

# ============================================================
# LAYOUT DASH
# ============================================================

app.layout = html.Div([

    html.H1(
        "Mortalidad en Colombia 2019",
        style={
            "textAlign": "center",
            "marginBottom": "30px"
        }
    ),

    dcc.Graph(figure=fig_mapa),

    dcc.Graph(figure=fig_lineas),

    dcc.Graph(figure=fig_barras),

    dcc.Graph(figure=fig_pie),

    html.H2("10 principales causas de muerte"),

    dash_table.DataTable(
        data=top_causas.to_dict("records"),
        columns=[
            {"name": "Código", "id": "COD_MUERTE"},
            {"name": "Causa", "id": "CAUSA_NOMBRE"},
            {"name": "Total", "id": "TOTAL"},
        ],
        style_table={"overflowX": "auto"},
        style_cell={
            "textAlign": "left",
            "padding": "10px"
        },
        style_header={
            "fontWeight": "bold"
        },
        page_size=10
    ),

    dcc.Graph(figure=fig_apiladas),

    dcc.Graph(figure=fig_histograma)

])

# ============================================================
# EJECUTAR APP
# ============================================================
from dash import Dash
import os

app = Dash(__name__)
server = app.server

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8050))
    app.run(host="0.0.0.0", port=port, debug=False)